"""add_water_log_table

Revision ID: 568a34269995
Revises: seed_food_items_001
Create Date: 2026-04-17 21:29:01.425328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '568a34269995'
down_revision: Union[str, Sequence[str], None] = 'seed_food_items_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('water_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('amount_ml', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_water_log_user_date', 'water_log', ['user_id', 'log_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_water_log_user_date', table_name='water_log')
    op.drop_table('water_log')
    # ### end Alembic commands ###
