"""initial_schema

Revision ID: b2407a8a1a76
Revises: 
Create Date: 2026-04-12 21:09:53.563908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2407a8a1a76'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('name_normalized', sa.String(length=256), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('serving_size_g', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('calories_kcal', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('protein_g', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('carbs_g', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('fat_g', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('fiber_g', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('sugar_g', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('is_veg', sa.Boolean(), nullable=False),
    sa.Column('is_egg', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_food_items_name_normalized', 'food_items', ['name_normalized'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('food_log_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('food_item_id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.String(length=16), nullable=False),
    sa.Column('quantity_g', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('calories_kcal', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('protein_g', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('carbs_g', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('fat_g', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('fiber_g', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['food_item_id'], ['food_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_food_log_user_date', 'food_log_entries', ['user_id', 'log_date'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('age', sa.SmallInteger(), nullable=False),
    sa.Column('gender', sa.String(length=16), nullable=False),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('current_weight_kg', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('goal_weight_kg', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('time_to_reach_goal_weeks', sa.SmallInteger(), nullable=False),
    sa.Column('experience_level', sa.String(length=16), nullable=False),
    sa.Column('activity_level', sa.String(length=16), nullable=False),
    sa.Column('diet_type', sa.String(length=16), nullable=False),
    sa.Column('wants_workout_split', sa.Boolean(), nullable=False),
    sa.Column('wants_diet_plan', sa.Boolean(), nullable=False),
    sa.Column('bmr_kcal', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('tdee_kcal', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('target_calories_kcal', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('bmi', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('protein_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('carbs_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('fat_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('weight_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('note', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'log_date', name='uq_weight_log_user_date')
    )
    op.create_index('idx_weight_log_user_date', 'weight_log', ['user_id', 'log_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_weight_log_user_date', table_name='weight_log')
    op.drop_table('weight_log')
    op.drop_table('user_profiles')
    op.drop_index('idx_food_log_user_date', table_name='food_log_entries')
    op.drop_table('food_log_entries')
    op.drop_table('users')
    op.drop_index('idx_food_items_name_normalized', table_name='food_items')
    op.drop_table('food_items')
    # ### end Alembic commands ###
