"""add_food_items_extended_columns

Revision ID: bc8e87178e50
Revises: 568a34269995
Create Date: 2026-06-27 15:13:10.604391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc8e87178e50'
down_revision: Union[str, Sequence[str], None] = '568a34269995'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_items', sa.Column('source', sa.String(length=32), nullable=True))
    op.add_column('food_items', sa.Column('source_id', sa.String(length=64), nullable=True))
    op.add_column('food_items', sa.Column('cuisine', sa.String(length=64), nullable=True))
    op.add_column('food_items', sa.Column('aliases', sa.Text(), nullable=True))
    op.add_column('food_items', sa.Column('saturated_fat_g', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('food_items', sa.Column('sodium_mg', sa.Numeric(precision=7, scale=2), nullable=True))
    op.add_column('food_items', sa.Column('calcium_mg', sa.Numeric(precision=7, scale=2), nullable=True))
    op.add_column('food_items', sa.Column('iron_mg', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('food_items', sa.Column('vitamin_c_mg', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('food_items', sa.Column('is_vegan', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food_items', 'is_vegan')
    op.drop_column('food_items', 'vitamin_c_mg')
    op.drop_column('food_items', 'iron_mg')
    op.drop_column('food_items', 'calcium_mg')
    op.drop_column('food_items', 'sodium_mg')
    op.drop_column('food_items', 'saturated_fat_g')
    op.drop_column('food_items', 'aliases')
    op.drop_column('food_items', 'cuisine')
    op.drop_column('food_items', 'source_id')
    op.drop_column('food_items', 'source')
    # ### end Alembic commands ###
